version: "2"
services:
  proxy:
    container_name: "nginx-proxy"
    build: ./docker/nginx-proxy/
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  mysql:
    container_name: "mysql"
    build: ./docker/mysql/
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/volums:/var/lib/mysql
      - ./docker/mysql/log/:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - VIRTUAL_HOST=mysql.dev
  php:
    build: ./docker/php7-imagick-httpd/
    tty: true
    volumes:
      - ./htdoc:/var/www/html
    links:
      - mysql
    environment:
      - VIRTUAL_HOST=web.local
