version: "2"
services:
  mysql:
    container_name: "mysql"
    build: ./docker/mysql/
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/volums:/var/lib/mysql
      - ./docker/mysql/log/:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
  php:
    build: ./docker/php7-imagick-httpd/
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./htdoc:/var/www/html
    links:
      - mysql
