version: "2"
services:
  mysql:
    container_name: "mysql"
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
  php:
    build: ./docker/php7-imagick-httpd/
    tty: true # 起動し続ける
    ports:
      - "8080:80"
    volumes:
      - ./htdoc:/var/www/html
    links:
      - mysql
